version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ../:/var/www/html/
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html/
  mysql:
    image: mysql:5.6.40
    command: --init-file /mysql/init.sql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/mysql/init.sql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword

    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
networks:
  frontend:
  backend: